### ISSUE TITLE
configure.ac is a bit messy

### ISSUE THREAD

**Issue by jplatte** [maekitalo/tntnet#43]
Reading through [configure.ac](https://github.com/maekitalo/tntnet/blob/master/configure.ac), I found several things done in multiple different ways throughout the file:
- Option testing with `test "$enable_option" = "yes"` and `test x$enable_option = xyes` (e.g. line 135 and line 149)
- Conditional code paths with `AS_IF` and the shell's `if ... then ... endif` (e.g. line 152 and line 196)

Also, the options `-Wall` and `-pedantic` are enabled (only) for the IBM C++ compiler. Why?

**Comment by maekitalo** [comment]
-Wall and -pedantic are not set for the IBM compiler. The test is in the else path of AS_IF.

The problem is, that the IBM compiler misinterprets at least -pedantic. The configure check thinks, that they are ok but building fails. Hence the exclusion of the IBM compiler.

And I guess it is a good idea to be more consistent. I will look at it.
